### ISSUE TITLE
Automatically fill in incident energy value.

### ISSUE THREAD

**Issue by stuartcampbell** [NSLS-II/PyXRF#162] opened 2019-07-30 20:24 UTC
For the automatic element finding, we should automatically enter the Incident Energy rather than the user typing it in.  Also, we can set the min to be 1.0 and the max to either be set to the incident energy or slightly higher (by a fixed amount).

In the "options" (top right of plot window) there is a 'high level energy' that should also default to the incident energy

@andrewmkiss Are there any other places in the GUI ?

**Comment by dmgav** [comment] 2019-07-31 20:21
It seems like HDF files do not contain information on the incident energy. The value may be found in the 'start' document (beamline_status/energy), so in principle it is possible to read it when loading data with Databroker, but it will remain unavailable when reading files. If it is important at this point, we can change the conversion program, so that all the metadata from the 'start' document is included in the HDF file, but it is better to review data formats used on other beamlines before changing the file format.

**Comment by stuartcampbell** [comment] 2019-07-31 20:31
We should also investigate any other more standard HDF5 based formats out there (e.g. Data Exchange and NeXus) rather than maintaining our own special format.

**Comment by dmgav** [comment] 2019-07-31 20:42
I think the quick fix is to automatically update the fields in respective dialog boxes so that incident energy had to be typed only once and range is set automatically.

**Comment by dmgav** [comment] 2019-08-02 13:59
The issue is resolved in pull request #163. The incident energy needs to be typed once in 'Find Elements Automatically' dialog box (Fit tab). It propagates to other dialog boxes automatically. The upper boundary for the range for element search is kept 0.8 higher than the incident energy, but may be changed manually.

**Comment by andrewmkiss** [comment] 2019-08-19 19:42
Thank you for propagating the energy.

What do you mean by the "upper boundary for the range for the element search is kept 0.8 higher than the incident energy"? It is common for us to scan a gold pattern at 12 keV. Gold has a binding energy at 11.919, and a fluorescence line at 9.7. 0.8*12 keV = 9.6 keV. Would gold be automatically found in the fitting?

**Comment by dmgav** [comment] 2019-11-19 18:44
The issue is fully resolved in https://github.com/NSLS-II/PyXRF/pull/194

**Closed by dmgav** 2019-11-19 18:44 UTC
