### ISSUE TITLE
PyXRF crashes if working directory does not match file location

### ISSUE THREAD

**Issue by andrewmkiss** [NSLS-II/PyXRF#160] opened 2019-06-19 13:37 UTC
It is frustrating for us and users when a file is loaded and pyxrf crashes because the working directory does not match the file path. The full file path is returned from the file browser, but pyxrf disregards this information and only looks at the file name. It would be great to remove this "working directory" and simply load a file and have pyxrf automatically find the working directory and set that parameter correctly.

pyxrf/view/fileio.enaml
`                    path = FileDialogEx.get_open_file_names(file_view, current_path=io_model.working_directory)
                    if path:
                        # only load one file
                        # 'temp' is used to reload the same file, otherwise file_name will not update
                        io_model.file_name = 'temp'
                        io_model.file_name = [item.split(sep_v)[-1] for item in path][0:1][0]
                        files_load.text = '{} is loaded.'.format(io_model.file_name)
`

**Comment by mrakitin** [comment] 2019-06-19 13:55
Here is the place in the code: https://github.com/NSLS-II/PyXRF/blob/e218632b7112468158971cd21c9d4e28279a3ade/pyxrf/view/fileio.enaml#L107-L113

**Comment by dmgav** [comment] 2019-07-31 14:04
The issue is addressed in pull request #161. Now Working Directory is tracking the location of currently open data file. When the program is first started, Working Directory can be manually selected as before, the only difference is that the field that displays the directory name is not editable. Once the first input file is opened, the 'Working Directory' button is disabled. There is no way to manually change the Working Directory after opening a file, therefore the behavior of the program remains consistent (working_directory is always matching the location the input file).

Two other changes:
-- The default file mask (```*.h5```) is added to the Open File dialog box, so that only ```.h5``` files are displayed by default. The ```*``` mask can also be selected from the menu to see or open files with different extensions.
-- If there is an error while opening a data file (wrong type of file is selected, etc.), a Message Box is displayed. Care should be taken not to run any processing before a valid input file is correctly loaded, since behavior of the program may be unpredictable. (Typically all the data dependent features should be deactivated until valid data is loaded.)

**Closed** 2019-08-09 15:01 UTC
